/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "stm32f103x6.h"
#include "Stm32_F103C6_GPIO_Driver.h"
#include "Stm32_F103C6_EXTI_Driver.h"

#include "../HAL/includes/keypad.h"
#include "../HAL/includes/lcd.h"


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

/*
void clock_init()
{

	// Enable clock GPIOA
	RCC_GPIOA_CLK_EN();

	// Enable clock GPIOB
	RCC_GPIOB_CLK_EN();

}

void GPIO_init()
{
	GPIO_PinConfig_t PinCfg ;

	// Configure PA1 as input floating

	PinCfg.GPIO_PinNumber = GPIO_PIN_1 ;
	PinCfg.GPIO_MODE = GPIO_MODE_INPUT_FLO;
	MCAL_GPIO_Init(GPIOA, &PinCfg);

	// Configure PA13 as input floating

	PinCfg.GPIO_PinNumber = GPIO_PIN_13 ;
	PinCfg.GPIO_MODE = GPIO_MODE_INPUT_FLO;
	MCAL_GPIO_Init(GPIOA, &PinCfg);

	// Configure PB1 as Output Push Pull

	PinCfg.GPIO_PinNumber = GPIO_PIN_1 ;
	PinCfg.GPIO_MODE = GPIO_MODE_OUTPUT_PP;
	PinCfg.GPIO_Output_Speed = GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIOB, &PinCfg);

	// Configure PB13 as Output Push Pull

	PinCfg.GPIO_PinNumber = GPIO_PIN_13 ;
	PinCfg.GPIO_MODE = GPIO_MODE_OUTPUT_PP;
	PinCfg.GPIO_Output_Speed = GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIOB, &PinCfg);

}
void my_wait(int x)
{
	uint32_t i,j;

	for (i = 0; i < x ; i++)
	{
		for(j = 0; j < 255 ; j++);
	}
}

int main(void)
{
	clock_init();
	GPIO_init();

	while(1)
	{
		// Single Pressing

		if(MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_1) == 0)
		{
			//Toggle Led on PB1
			MCAL_GPIO_TogglePin(GPIOB, GPIO_PIN_1);

			while(MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_1) == 0);
		}

		// Multi Pressing

		if(MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_13) == 1)
		{
			//Toggle Led on PB1
			MCAL_GPIO_TogglePin(GPIOB, GPIO_PIN_13);


		}

		my_wait(1);
	}
}
*/
uint8_t IRQ_Flag = 0;

void my_wait(int x)
{
	uint32_t i,j;

	for (i = 0; i < x ; i++)
	{
		for(j = 0; j < 255 ; j++);
	}
}

void EXTI9_Callback(void)
{
	IRQ_Flag = 1;
	HAL_LCD_WRITE_STRING("IRQ EXTI9 has happened _|-");
	my_wait(1000);
}

int main(void)
{
	//Enable Clock
	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();
	AFIO_CLK_EN();

	HAL_LCD_INIT();
	HAL_LCD_CLEAR_SCREEN();

	HAL_LCD_WRITE_STRING("Khloud Mohamed");
	my_wait(30);
	HAL_LCD_CLEAR_SCREEN();

	EXTI_PinConfig_t EXTI_CFG;
	EXTI_CFG.EXTI_PIN = EXTI9PB9;
	EXTI_CFG.Trigger_Case = EXTI_Trigger_RISING;
	EXTI_CFG.P_IRQ_CallBack = EXTI9_Callback;
	EXTI_CFG.IRQ_EN = EXTI_IRQ_Enable;

	MCAL_EXTI_GPIO_Init(&EXTI_CFG);

	IRQ_Flag = 1;

    while(1)
    {
    	if(IRQ_Flag)
    	{
    		HAL_LCD_CLEAR_SCREEN();
    		IRQ_Flag = 0;

    	}
    	my_wait(1000);
    }
	return 0;
}
